mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.example.pojo
spring:
    application:
        name: druid-demo
    datasource:
        # 数据库相关配置
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis01
        username: root
        password: root
        druid:
            # 初始化连接数量
            initial-size: 5
            # 最小线连接数量
            min-idle: 5
            # 最大连接数量
            max-active: 20
            # 获取连接时最大等待时间，单位毫秒
            max-wait: 60000
            #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
            min-evictable-idle-time-millis: 30000
            #用来检测连接是否有效的sql 必须是一个查询语句
            #mysql中为 select 'x'
            #oracle中为 select 1 from dual
            validation-query: select 'x'
            #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-borrow: false
            #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为tru
            test-on-return: false
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            # 配置监拉统计挡成的filters. stat: 监控统计、Log4j:日志记录、waLL: 防御sqL注入
            filters: stat,wall,log4j2
            # 配置后台监控
            stat-view-servlet:
                # 允许访问的地址，这里因为时本地所以配置当前机器
                allow: 127.0.0.1
                # 是否开启访问
                enabled: true
                # 是否能够重置数据
                reset-enable: false
                # 管理页面登陆的用户名
                login-username: admin
                # 管理页面登陆的密码
                login-password: admin
